apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: marker
  name: marker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: marker
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: marker
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: cm-nginx
          mountPath: "/usr/share/nginx/html/"
          readOnly: true
      volumes:
      - name: cm-nginx
        configMap: 
          name: cm-nginx
status: {}

---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: LoadBalancer
  selector:
    app: marker
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
