apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: marker
  name: marker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: marker
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: marker
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
        resources: {}
status: {}

---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: NodePort
  selector:
    app: marker
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007
