apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80

---
apiVersion: v1
kind: Pod
metadata:
  name: httpd
spec:
  containers:
  - name: nginx
    image: pritamkhergade/dell:student-ui-tomcat
    ports:
    - containerPort: 8080
